// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.19.4
// source: words.proto

package words

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckSensitiveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *CheckSensitiveRequest) Reset() {
	*x = CheckSensitiveRequest{}
	mi := &file_words_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSensitiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSensitiveRequest) ProtoMessage() {}

func (x *CheckSensitiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_words_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSensitiveRequest.ProtoReflect.Descriptor instead.
func (*CheckSensitiveRequest) Descriptor() ([]byte, []int) {
	return file_words_proto_rawDescGZIP(), []int{0}
}

func (x *CheckSensitiveRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type CheckSensitiveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Words     []string `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
	Sensitive bool     `protobuf:"varint,2,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
}

func (x *CheckSensitiveResponse) Reset() {
	*x = CheckSensitiveResponse{}
	mi := &file_words_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSensitiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSensitiveResponse) ProtoMessage() {}

func (x *CheckSensitiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_words_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSensitiveResponse.ProtoReflect.Descriptor instead.
func (*CheckSensitiveResponse) Descriptor() ([]byte, []int) {
	return file_words_proto_rawDescGZIP(), []int{1}
}

func (x *CheckSensitiveResponse) GetWords() []string {
	if x != nil {
		return x.Words
	}
	return nil
}

func (x *CheckSensitiveResponse) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

var File_words_proto protoreflect.FileDescriptor

var file_words_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x77,
	0x6f, 0x72, 0x64, 0x73, 0x22, 0x2b, 0x0a, 0x15, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x6e,
	0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x22, 0x4c, 0x0a, 0x16, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x6e, 0x73, 0x69, 0x74,
	0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x77,
	0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x64,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x32,
	0x56, 0x0a, 0x05, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x4d, 0x0a, 0x0e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x12, 0x1c, 0x2e, 0x77, 0x6f, 0x72,
	0x64, 0x73, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x77, 0x6f, 0x72, 0x64, 0x73,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x76, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x77, 0x6f, 0x72,
	0x64, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_words_proto_rawDescOnce sync.Once
	file_words_proto_rawDescData = file_words_proto_rawDesc
)

func file_words_proto_rawDescGZIP() []byte {
	file_words_proto_rawDescOnce.Do(func() {
		file_words_proto_rawDescData = protoimpl.X.CompressGZIP(file_words_proto_rawDescData)
	})
	return file_words_proto_rawDescData
}

var file_words_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_words_proto_goTypes = []any{
	(*CheckSensitiveRequest)(nil),  // 0: words.CheckSensitiveRequest
	(*CheckSensitiveResponse)(nil), // 1: words.CheckSensitiveResponse
}
var file_words_proto_depIdxs = []int32{
	0, // 0: words.Words.CheckSensitive:input_type -> words.CheckSensitiveRequest
	1, // 1: words.Words.CheckSensitive:output_type -> words.CheckSensitiveResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_words_proto_init() }
func file_words_proto_init() {
	if File_words_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_words_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_words_proto_goTypes,
		DependencyIndexes: file_words_proto_depIdxs,
		MessageInfos:      file_words_proto_msgTypes,
	}.Build()
	File_words_proto = out.File
	file_words_proto_rawDesc = nil
	file_words_proto_goTypes = nil
	file_words_proto_depIdxs = nil
}
